FORMAT: 1A
HOST: http://openlocationsapi-openlocationsapi.apps.us-east-1.starter.openshift-online.com/

# Open Locations API (OLAPI)

OLAPI is a simple RESTful API developed by Iddriss O. Juma using Nodejs+Mongodb. It enables to 
query for locations i.e. cities, countries, villages, hotels, rivers, mountains etc via 
simple REST get/post requests.

OLAPI is opensource, it is released under ISC/BSD license. have fun!